version: '2'
services:
    logobd-app:
        image: logobd
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://logobd-mysql:3306/logobd?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    logobd-mysql:
        extends:
            file: mysql.yml
            service: logobd-mysql
